/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import core.Cards;
import core.Encoder;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Red
 */
public class App extends javax.swing.JFrame {
    
    private Encoder encoder;
    private CardViewer cardViewer;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        cardViewer = null;
    }
    
    public App(Encoder encoder) {
        initComponents();
        cardViewer = null;
        this.encoder = encoder;
    }
    
    public void addToJPanel1(CardViewer comp)
    {
        this.jPanel1.add(comp);
        int w = (this.getWidth() + comp.getPreferredSize().width);//171
        int h = (this.getHeight() + comp.getPreferredSize().height);//144

        Dimension d = new Dimension(w, h);
        this.jPanel1.setPreferredSize(d);
        this.jPanel1.setMinimumSize(d);
        
        Dimension d2 = new Dimension(w + this.getMinimumSize().width, h + this.getMinimumSize().height);
        this.setMinimumSize(d2);
        this.setPreferredSize(d2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        toEncrypt = new javax.swing.JLabel();
        textToEncrypt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        encryptButton = new javax.swing.JButton();
        encrypted = new javax.swing.JLabel();
        encryptedText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        fromEncrypted = new javax.swing.JLabel();
        textToDecrypt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        decryptButton = new javax.swing.JButton();
        decrypted = new javax.swing.JLabel();
        decryptedText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(1, 1));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new java.awt.GridLayout(11, 1));

        toEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toEncrypt.setText(" Message à chiffrer");
        toEncrypt.setAlignmentX(0.5F);
        jPanel3.add(toEncrypt);

        textToEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(textToEncrypt);

        jPanel7.setLayout(new java.awt.BorderLayout());

        encryptButton.setText("Chiffrer");
        encryptButton.setMaximumSize(new java.awt.Dimension(81, 23));
        encryptButton.setMinimumSize(new java.awt.Dimension(81, 23));
        encryptButton.setPreferredSize(new java.awt.Dimension(81, 23));
        encryptButton.setRequestFocusEnabled(false);
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });
        jPanel7.add(encryptButton, java.awt.BorderLayout.LINE_START);

        jPanel3.add(jPanel7);

        encrypted.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        encrypted.setText(" Message chiffré");
        jPanel3.add(encrypted);

        encryptedText.setEditable(false);
        jPanel3.add(encryptedText);
        jPanel3.add(jPanel6);

        fromEncrypted.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fromEncrypted.setText(" Message à déchiffrer");
        jPanel3.add(fromEncrypted);
        jPanel3.add(textToDecrypt);

        jPanel5.setLayout(new java.awt.BorderLayout());

        decryptButton.setText("Déchiffrer");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });
        jPanel5.add(decryptButton, java.awt.BorderLayout.LINE_START);

        jPanel3.add(jPanel5);

        decrypted.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        decrypted.setText(" Message déchiffré");
        jPanel3.add(decrypted);

        decryptedText.setEditable(false);
        jPanel3.add(decryptedText);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);

        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        String tmp = textToEncrypt.getText();
        if(!tmp.equals(""))
        {
            tmp = encoder.encrypt(tmp);
            this.encryptedText.setText(tmp);
        }
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        String tmp = textToDecrypt.getText();
        if(!tmp.equals(""))
        {
            tmp = encoder.decrypt(tmp);
            this.decryptedText.setText(tmp);
        }
    }//GEN-LAST:event_decryptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptButton;
    private javax.swing.JLabel decrypted;
    private javax.swing.JTextField decryptedText;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel encrypted;
    private javax.swing.JTextField encryptedText;
    private javax.swing.JLabel fromEncrypted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField textToDecrypt;
    private javax.swing.JTextField textToEncrypt;
    private javax.swing.JLabel toEncrypt;
    // End of variables declaration//GEN-END:variables
}
