/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import core.Cards;
import core.Encoder;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Red
 */
public class App extends javax.swing.JFrame {
    
    private Cards cards;
    private Encoder encoder;
    private CardViewer cardViewer;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        this.cards      = null;
        this.encoder    = null;
        this.cardViewer = null;
    }
    
    public App(Cards cards, Encoder encoder, CardViewer cv) {
        initComponents();
        this.cards      = cards;
        this.encoder    = encoder;
        this.cardViewer = cv;
        setCardViewer(cv);
    }
    
    private void setCardViewer(CardViewer cv)
    {
        this.cardViewer = cv;
        this.jPanel1.add(cv);
        int w = (this.getWidth() + cv.getPreferredSize().width);//171
        int h = (this.getHeight() + cv.getPreferredSize().height);//144

        Dimension d = new Dimension(w, h);
        this.jPanel1.setPreferredSize(d);
        this.jPanel1.setMinimumSize(d);
        
        Dimension d2 = new Dimension(w + this.getMinimumSize().width, h + this.getMinimumSize().height);
        this.setMinimumSize(d2);
        this.setPreferredSize(d2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        encryptButton = new javax.swing.JButton();
        textToEncrypt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        encryptedText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        decryptButton = new javax.swing.JButton();
        textToDecrypt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        decryptedText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        mixColors = new javax.swing.JButton();
        mixValues = new javax.swing.JButton();
        mix = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(1, 1));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 1, 3));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Message à chiffrer"));
        jPanel7.setLayout(new java.awt.BorderLayout());

        encryptButton.setText("Chiffrer");
        encryptButton.setMaximumSize(new java.awt.Dimension(81, 23));
        encryptButton.setMinimumSize(new java.awt.Dimension(81, 23));
        encryptButton.setPreferredSize(new java.awt.Dimension(105, 23));
        encryptButton.setRequestFocusEnabled(false);
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });
        jPanel7.add(encryptButton, java.awt.BorderLayout.LINE_END);

        textToEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.add(textToEncrypt, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Message chiffré"));
        jPanel6.setLayout(new java.awt.BorderLayout());

        encryptedText.setEditable(false);
        jPanel6.add(encryptedText, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Message à déchiffrer"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        decryptButton.setText("Déchiffrer");
        decryptButton.setPreferredSize(new java.awt.Dimension(105, 25));
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });
        jPanel5.add(decryptButton, java.awt.BorderLayout.LINE_END);
        jPanel5.add(textToDecrypt, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Message déchiffré"));
        jPanel8.setLayout(new java.awt.BorderLayout());

        decryptedText.setEditable(false);
        jPanel8.add(decryptedText, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mélanger"));
        jPanel4.setLayout(new java.awt.GridLayout(10, 0, 1, 0));

        mixColors.setText("Couleurs");
        mixColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixColorsActionPerformed(evt);
            }
        });
        jPanel4.add(mixColors);

        mixValues.setText("Valeurs");
        mixValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixValuesActionPerformed(evt);
            }
        });
        jPanel4.add(mixValues);

        mix.setText("Aléatoire");
        mix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixActionPerformed(evt);
            }
        });
        jPanel4.add(mix);

        jLabel5.setText(" ");
        jPanel4.add(jLabel5);

        backup.setText("Défaut");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });
        jPanel4.add(backup);

        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        String tmp = textToEncrypt.getText().toUpperCase();
        if(!tmp.equals(""))
        {
            tmp = encoder.encrypt(tmp);
            this.encryptedText.setText(tmp);
        }
        this.cardViewer.repaint();
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        String tmp = textToDecrypt.getText().toUpperCase();
        if(!tmp.equals(""))
        {
            tmp = encoder.decrypt(tmp);
            this.decryptedText.setText(tmp);
        }
        this.cardViewer.repaint();
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void mixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixActionPerformed
        this.cards.randomMix();
        this.cardViewer.repaint();
    }//GEN-LAST:event_mixActionPerformed

    private void mixColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixColorsActionPerformed
        this.cards.colorMix();
        this.cardViewer.repaint();
    }//GEN-LAST:event_mixColorsActionPerformed

    private void mixValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixValuesActionPerformed
        this.cards.valueMix();
        this.cardViewer.repaint();
    }//GEN-LAST:event_mixValuesActionPerformed

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
        this.cards.loadBackup();
        this.cardViewer.repaint();
    }//GEN-LAST:event_backupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backup;
    private javax.swing.JButton decryptButton;
    private javax.swing.JTextField decryptedText;
    private javax.swing.JButton encryptButton;
    private javax.swing.JTextField encryptedText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton mix;
    private javax.swing.JButton mixColors;
    private javax.swing.JButton mixValues;
    private javax.swing.JTextField textToDecrypt;
    private javax.swing.JTextField textToEncrypt;
    // End of variables declaration//GEN-END:variables
}
