/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import core.Card;
import core.Cards;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Red
 */
public class CardViewer extends javax.swing.JPanel {

    private Cards cards;
    private int rows;
    private int cols;
    private int rowsFactor = 14;
    private int colsFactor = 40;
    private int size;
    private int index;
    /**
     * Creates new form CardViewer
     */
    public CardViewer() {
        initComponents();
    }
    public CardViewer(Cards cards) {
        initComponents();
        this.cards = cards;
        this.rows = 1;
        this.cols = 1;
        this.size = 0;
        this.index = 0;
        this.jPanel1.setPreferredSize(new Dimension(Card.WIDTH*6, 126));
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        Graphics g2 = this.jPanel1.getGraphics();
        
        this.rows = this.jPanel1.getWidth()/ (Card.WIDTH);
        this.cols = this.jPanel1.getHeight()/ (Card.HEIGHT);
        if((this.rows*this.cols) >= this.cards.count())
        {
            index = 0;
        }
        int k = index;
        for(int i=0 ; i <this.rows  ; i++)
        {
            for(int j=0 ; j<this.cols ; j++)
            {
                int x = 3 + this.jPanel1.getX() + (i * (Card.WIDTH));
                int y = this.jPanel1.getY() + (j * (Card.HEIGHT));
                if(k < this.cards.count())
                {
                    g.drawImage(cards.get(k).getImg(), x, y, this);
                    g.setColor(Color.WHITE);
                    g.fillRect(x+2, y+Card.HEIGHT-13, 32, 12);
                    g.setColor(Color.BLACK);
                    g.drawString((k+1) + "/" + this.cards.count(), x+2, y+Card.HEIGHT-2);
                }
                k++;
            }
        }
        boolean b = !((this.cols * this.rows) >= this.cards.count());
        this.jPanel2.setVisible(b);            
        this.jPanel3.setVisible(b);
        this.jPanel4.setVisible(b);

        if(this.cols > 0 && this.rows > 0)
        {
            this.jLabel1.setText("page: " + (1+(this.index/this.rows)) + "/" + (this.cards.count()/this.rows));
        }
    }
    /*
    @Override
    public Component add(Component comp)
    {
        super.add(comp);
        int w = (rowsFactor + comp.getPreferredSize().width) * cols;//171
        int h = (colsFactor + comp.getPreferredSize().height) * rows;//144

        Dimension d = new Dimension(w, h);
        this.setPreferredSize(d);
        //this.setMinimumSize(d);
        
        return comp;
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(10, 97));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 97));
        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.CardLayout());

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, "card2");

        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.CardLayout());

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, "card2");

        add(jPanel3, java.awt.BorderLayout.EAST);

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        add(jPanel4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        //System.out.println(this.jPanel1.getWidth() + " " + this.jPanel1.getHeight());
    }//GEN-LAST:event_formComponentResized

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.index < (this.cards.count()-this.rows))
        {
            this.index += this.rows;
        }
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.index >= this.rows)
        {
            this.index -= this.rows;
        }
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
