/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Red
 */
public class DeckViewer extends javax.swing.JPanel {

    /**
     * Creates new form CardViewer
     */
    public DeckViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelEast = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanelEast.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        jPanelEast.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trier"));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        jPanelEast.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1);

        jPanelEast.add(jPanel4);

        add(jPanelEast, java.awt.BorderLayout.EAST);

        jPanelCenter.setLayout(new java.awt.GridLayout(2, 1));
        add(jPanelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelEast;
    // End of variables declaration//GEN-END:variables
}
