/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Red
 */
public class SeedViewer extends javax.swing.JFrame {

    private JButton button1;
    private JButton button2;
    private JTextField jText;
    private JLabel jNoti;
    
    public SeedViewer(String title, String but1, String but2) {
        initComponents();
        this.setTitle(title);
        jText   = this.jTextField2;
        jNoti   = this.jLabel1;
        button1 = new JButton(but1);
        button2 = new JButton(but2);
        this.jPanelEast.add(button1);
        this.jPanelEast.add(button2);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) 
            {
                dispose();
            }
        });
    }

    public JButton getButton1() {
        return button1;
    }

    public JButton getButton2() {
        return button2;
    }

    public JTextField getjText() {
        return jText;
    }

    public JLabel getjNoti() {
        return jNoti;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelEast = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 80));
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setLayout(new java.awt.GridLayout(2, 1, 1, 2));
        jPanelCenter.add(jTextField2);
        jPanelCenter.add(jLabel1);

        jPanel1.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelEast.setLayout(new java.awt.GridLayout(2, 1, 1, 2));
        jPanel1.add(jPanelEast, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
